# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            IDEwtf
tagline:          'A Jekyll theme'
description:      'We write about things that happen to our IDEs.'

author:
  name:           'Mariusz Ozdoba'

paginate:         5


